# Generated by Django 4.2.4 on 2023-08-19 04:10
import pandas as pd
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    def insert_init_data(apps, shcema_editor):
        df = pd.read_csv('credit/migrations/data.csv')
        arr_banks = df['institucion'].unique()
        Bank = apps.get_model('credit', 'Bank')
        for i in arr_banks:
            Bank.objects.create(name=i)

    def undo_insert_data(apps, shcema_editor):
        Bank = apps.get_model('credit', 'Bank')
        Bank.objects.all().delete()

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RunPython(insert_init_data,reverse_code=undo_insert_data)
    ]
