# Generated by Django 4.2.4 on 2023-08-19 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.PositiveSmallIntegerField(choices=[(1, 'Moneda extranjera'), (2, 'Moneda nacional'), (3, 'UDIS')], default=2)),
                ('credit_status', models.PositiveSmallIntegerField(choices=[(1, 'Vencido'), (2, 'Vigente')], default=2)),
                ('total', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.bank')),
            ],
        ),
    ]
